Fix "LookupError: unknown encoding: mbcs" on Linux
The fix is required to make NVDA Python code Linux compatible.
Otherwise the code fails with the exception.

      File "src/nvda-synthDriver/__init__.py", line 55, in <module>
        module_dir=os.path.dirname(__file__.decode("mbcs"))
    LookupError: unknown encoding: mbcs